STORAGE_DIR = "/home/shared_storage"
MODELS_DIR = "/home/shared_storage/models"
HUGGINGFACE_DIR = "/home/shared_storage/huggingface"
RESULTS_DATA_DIR = "/home/shared_storage/results/data"
RESULTS_PLOTS_DIR = "/home/shared_storage/results/plots"
